#### DoD Additions ####
#Kraken
Kraken:
  size: 0.02
  health: 1.0
  damage: 0.6
  health per star: 0.1
  damage per star: 0.5
  attack speed per star: 0.5
  Ocean:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 0.6
        1: 0.65
        2: 0.75
        3: 0.8
        4: 0.85
        5: 0.9
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 0.75
        1: 0.8
        2: 0.85
        3: 0.9
        4: 0.95
        5: 1
# Molluscan
Molluscan:
  size: 0.02
  health: 1.0
  damage: 0.6
  infusion: 
      Fire: 0
  Ocean:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.2
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 0.75
        1: 0.8
        2: 0.85
        3: 0.9
        4: 0.95
        5: 1
# Giant Viper
Giant Viper:
  size: 0.02
  infusion: 
      Fire: 0
  Ocean:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.2
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25