#### DoD Monsters ####
## Vanilla Bosses
Eikthyr:
  size: 0.02
  Meadows:
    key_defeated_eikthyr:
      health:
          0: 2
          1: 3
          2: 4
          3: 6
          4: 8
          5: 10
      damage: 
          0: 2
          1: 3
          2: 4
          3: 6
          4: 8
          5: 10
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      movement speed: 
          0: 1.1
          1: 1.2
          2: 1.3
          3: 1.4
          4: 1.5
          5: 1.6
The Elder:
  size: 0.02
  BlackForest:
    key_defeated_gdking:
      health:
          0: 1.4
          1: 1.8
          2: 2.2
          3: 2.8
          4: 3.4
          5: 4
      damage: 
          0: 1.4
          1: 1.8
          2: 2.2
          3: 2.8
          4: 3.4
          5: 4
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      movement speed: 
          0: 1.1
          1: 1.2
          2: 1.3
          3: 1.4
          4: 1.5
          5: 1.6
Bonemass:
  size: 0.02
  Swamp:
    key_defeated_bonemass:
      health:
          0: 1.25
          1: 1.5
          2: 1.75
          3: 2
          4: 2.25
          5: 2.5
      damage: 
          0: 1.25
          1: 1.5
          2: 1.75
          3: 2
          4: 2.25
          5: 2.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      movement speed: 
          0: 1.1
          1: 1.2
          2: 1.3
          3: 1.4
          4: 1.5
          5: 1.6
Moder:
  size: 0.02
  Mountain:
    key_defeated_dragon:
      health:
          0: 1.25
          1: 1.45
          2: 1.65
          3: 1.85
          4: 2.05
          5: 2.25
      damage: 
          0: 1.25
          1: 1.45
          2: 1.65
          3: 1.85
          4: 2.05
          5: 2.25
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      movement speed:
          0: 1.1
          1: 1.2
          2: 1.3
          3: 1.4
          4: 1.5
          5: 1.6
GoblinKing:
  size: 0.02
  Plains:
    key_defeated_goblinking:
      health:
          0: 1.25
          1: 1.4
          2: 1.55
          3: 1.7
          4: 1.85
          5: 2
      damage: 
          0: 1.25
          1: 1.4
          2: 1.55
          3: 1.7
          4: 1.85
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      movement speed: 
          0: 1.1
          1: 1.2
          2: 1.3
          3: 1.4
          4: 1.5
          5: 1.6
## Living Water
LivingWater:
    size: 0
    infusion: 
        Fire: 0
        Frost: 0
        Lightning: 15
        Spirit: 15
        Poison: 0
        Chaos: 0