#### DoD Vanilla Changes ####
# Troll
Troll:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Ghost
Ghost:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
#Skeleton
Skeleton:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
#Rancid Remains
Rancid Remains:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf
Greydwarf:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Shaman
Greydwarf Shaman:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Brute
Greydwarf Brute:
  size: 0.02
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Tree Spider
Tree Spider:
  size: 0.02
  health: 0.5
  damage: 0.5
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 0
      Spirit: 9
      Poison: 18
      Chaos: 9
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 0.5
          1: 0.55
          2: 0.6
          3: 0.65
          4: 0.7
          5: 0.75
      damage: 
          0: 0.4
          1: 0.5
          2: 0.6
          3: 0.7
          4: 0.8
          5: 0.9
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 0.75
          1: 0.79
          2: 0.83
          3: 0.87
          4: 0.91
          5: 0.95
      damage: 
          0: 0.6
          1: 0.63
          2: 0.69
          3: 0.72
          4: 0.75
          5: 0.78
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25   
# Stormling
Stormling:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 36
      Spirit: 0
      Poison: 0
      Chaos: 0
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25 
# Hobgoblin
Hobgoblin:
  size: 0.02
  infusion: 
      Fire: 12
      Frost: 12
      Lightning: 12
      Spirit: 12
      Poison: 12
      Chaos: 12
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25 
# Ent
Ent:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 24
      Spirit: 0
      Poison: 12
      Chaos: 24
  Black Forest:
    nokey_defeated_gdking:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_gdking:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25 