# Weapon

fire starter:
  slot: weapon
  gem: red
  power: [5, 10, 15]

ice heart:
  slot: weapon
  gem: blue
  power: [5, 10, 15]

snake bite:
  slot: weapon
  gem: green
  power: [5, 10, 15]

shadow hit:
  slot: weapon
  gem: black
  power: [2, 3, 4]

vampire:
  slot: weapon
  gem: yellow
  power: [6, 8, 10]

berserk:
  slot: weapon
  gem: purple
  power: [1, 2, 3]

# Chest

defender:
  slot: chest
  gem: red
  power: [1, 2, 3]

vitality:
  slot: chest
  gem: blue
  power: [3, 5, 7]

regeneration:
  slot: chest
  gem: green
  power: [1, 2, 3]

mirror:
  slot: chest
  gem: black
  power: [2, 4, 6]

# Legs

sprinter:
  slot: legs
  gem: red
  power: [3, 5, 7]

ninja:
  slot: legs
  gem: black
  power: [12, 14, 16]

nimble:
  slot: legs
  gem: blue
  power: [7, 9, 11]

marathon:
  slot: legs
  gem: yellow
  power: [7, 9, 11]

# Utility

power recovery:
  slot: utility
  gem: green
  power: [10, 12, 15]

comfortable:
  slot: utility
  gem: yellow
  power: [3, 5, 7]

hercules:
  slot: utility
  gem: purple
  power: [10, 15, 20]

glowing spirit:
  slot: utility
  gem: blue
  power: [4, 6, 8]

# Head

explorer:
  slot: head
  gem: green
  power: [10, 15, 20]

student:
  slot: head
  gem: red
  power: [2, 3, 5]

resilience:
  slot: head
  gem: yellow
  power: [5, 7, 9]

gourmet:
  slot: head
  gem: purple
  power: [10, 13, 16]

merciful death:
  slot: head
  gem: blue
  power: [10, 15, 20]

# Bow

endless arrows:
  slot: bow
  gem: red
  power: [4, 6, 8]

necromancer:
  slot: bow
  gem: green
  power: [3, 5, 7]

master archer:
  slot: bow
  gem: purple
  power: [4, 6, 8]

stealth archer:
  slot: bow
  gem: black
  power: [20, 35, 50]

# Cloak

glider:
  slot: cloak
  gem: green
  power: [3, 5, 7]

inconspicuous:
  slot: cloak
  gem: black
  power: [10, 15, 20]

turtle shell:
  slot: cloak
  gem: yellow
  power: [8, 10, 12]

# Shield

unfazed:
  slot: shield
  gem: blue
  power: [10, 15, 20]

parry master:
  slot: shield
  gem: purple
  power: [5, 8, 10]

avoidance:
  slot: shield
  gem: yellow
  power: [1, 2, 3]

tank:
  slot: shield
  gem: black
  power: [4, 6, 8]

pain tolerance:
  slot: shield
  gem: red
  power: [1, 2, 3]

# Tool

unbreakable:
  slot: tool
  gem: purple
  power: [40, 50, 60]

# Boss  

lightning speed:
  slot: all
  gem: eikthyr
  power:
    movement speed: 30
    min cooldown: 90
    max cooldown: 120
    duration: 8
    attack speed: 100
    stamina: 50
  unique: true

rooted revenge:
  slot: all
  gem: elder
  power:
    bonus damage: 25
    min cooldown: 150
    max cooldown: 240
    duration: 8
    range: 10
  unique: true

poisonous drain:
  slot: all
  gem: bonemass
  power:
    healing increase: 100
    min cooldown: 180
    max cooldown: 210
    duration: 8
    poison damage: 40
    life steal: 20
  unique: true

icy protection:
  slot: all
  gem: moder
  power:
    damage reduction: 90
    min cooldown: 180
    max cooldown: 210
    duration: 8
    drakes: 3
  unique: true

fiery doom:
  slot: all
  gem: yagluth
  power:
    stagger chance: 30
    min cooldown: 180
    max cooldown: 240
    duration: 8
    fire damage: 200
  unique: true

# Gem Spawn

gems:
  meadows:
    green: 0.6
    black: 0.02
    purple: 0.02
    blue: 0.02
    yellow: 0.02
    red: 0.02
  black forest:
    green: 0.02
    black: 0.6
    purple: 0.02
    blue: 0.02
    yellow: 0.02
    red: 0.02
  swamp:
    green: 0.02
    black: 0.02
    purple: 0.6
    blue: 0.02
    yellow: 0.02
    red: 0.02
  mountain:
    green: 0.02
    black: 0.02
    purple: 0.02
    blue: 0.6
    yellow: 0.02
    red: 0.02
  plains:
    green: 0.02
    black: 0.02
    purple: 0.2
    blue: 0.02
    yellow: 0.6
    red: 0.02
  mistlands:
    green: 0.02
    black: 0.02
    purple: 0.6
    blue: 0.02
    yellow: 0.02
    red: 0.02
  deep north:
    green: 0.02
    black: 0.02
    purple: 0.02
    blue: 0.6
    yellow: 0.02
    red: 0.02
  ash lands:
    green: 0.02
    black: 0.02
    purple: 0.02
    blue: 0.02
    yellow: 0.02
    red: 0.6