using System.Collections.Generic;
using UnityEngine;
using HarmonyLib;
using System.Reflection;
using System;

namespace DoDMonsters
{
    [HarmonyPatch]
    public class DoDLocal
    {
        private static Localization lcl;
        public static Dictionary<string, string> t;
        private static Dictionary<string, string> english = new Dictionary<string, string>() {

			{"animal_sheep_dod", "Sheep"},
			{"animal_goat_dod", "Goat"},
			{"animal_goose_dod", "Goose"},
			{"animal_penguin_dod", "Penguin"},
			{"animal_salamander_dod", "Fire Salamander"},
			{"animal_turtle_dod", "Box Turtle"},
			{"animal_rat_dod", "Rat"},
			{"animal_greenlizard_dod", "Green Lizard"},
			{"animal_brownlizard_dod", "Brown Lizard"},
			{"animal_spottedlizard_dod", "Spotted Lizard"},
			{"animal_greenfrog_dod", "Green Frog"},
			{"animal_blackfrog_dod", "Black Frog"},
			{"animal_spottedfrog_dod", "Spotted Frog"},
			{"animal_greyrabbit_dod", "Grey Rabbit"},
			{"animal_brownrabbit_dod", "Brown Rabbit"},
			{"animal_giantsnail_dod", "Giant Snail"},
			{"item_token_skull_dod", "Skull Token"},
			{"item_token_skull_description_dod", "Knarr the Trader likes these."},

			{"npc_skugga_dod", "Skugga"},
            {"npc_einherjar_dod", "Einherjar"},

			{"item_walnut_dod", "Walnuts"},
            {"item_walnuts_description_dod", "Gatherd from a Walnut Tree in the Mistlands."},
            {"item_apple_dod", "Apples"},
            {"item_apple_description_dod", "Gatherd from an Apple Tree in the Mistlands."},
            {"item_redberries_dod", "Cherries"},
            {"item_redberries_description_dod", "Gatherd from a Cherry Tree in the Mistlands."},

            {"item_shield_bgskull_dod", "Bhygshan's Broken Shield"},
            {"item_shield_bgskull_description_dod", "Used to be Bhygshan's shield before you broke it while fighting him. Wonder if you can fix it."},
            {"item_shield_byagluth_dod", "Broken Shield"},
            {"item_shield_byagluth_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_bskir_dod", "Broken Shield"},
            {"item_shield_bskir_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_bmoder_dod", "Broken Shield"},
            {"item_shield_bmoder_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_bfarkas_dod", "Broken Shield"},
            {"item_shield_bfarkas_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_bbonemass_dod", "Broken Shield"},
            {"item_shield_bbonemass_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_belder_dod", "Broken Shield"},
            {"item_shield_belder_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_bbitterstump_dod", "Broken Shield"},
            {"item_shield_bbitterstump_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_beikthyr_dod", "Broken Shield"},
            {"item_shield_beikthyr_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},
            {"item_shield_brambone_dod", "Broken Shield"},
            {"item_shield_brambone_description_dod", "Wonder if you can fix it. Feel free to offer suggestions for this item."},

            {"item_shield_yagluth_dod", "Deathgate"},
            {"item_shield_yagluth_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_skir_dod", "Curator Ward"},
            {"item_shield_skir_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_moder_dod", "Perfect Storm"},
            {"item_shield_moder_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_farkas_dod", "Frozen Light"},
            {"item_shield_farkas_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_bonemass_dod", "Ghostly Wall"},
            {"item_shield_bonemass_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_bhygshan_dod", "Vortex, Conservator of the Dead"},
            {"item_shield_bhygshan_description_dod", "You repaired Bhygshans Shield, congratulations! Feel free to offer suggestions for this item."},
            {"item_shield_elder_dod", "Ironbark"},
            {"item_shield_elder_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_bitterstump_dod", "Darkheart"},
            {"item_shield_bitterstump_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_eikthyr_dod", "Thundercloud"},
            {"item_shield_eikthyr_description_dod", "Feel free to offer suggestions for this item."},
            {"item_shield_rambone_dod", "Enforcer"},
            {"item_shield_rambone_description_dod", "Feel free to offer suggestions for this item."},

            {"item_mace_bhygshan_dod", "Defiled Warmace"},
            {"item_mace_bhygshan_description_dod", "Defiled Warmace. Feel free to offer suggestions for this description."},
            {"item_bow_blackforest_dod", "Hornet"},
            {"item_bow_blackforest_description_dod", "Hornet. Feel free to offer suggestions for this description."},
            {"item_bow_swamp_dod", "Sting, Serpent of Regret"},
            {"item_bow_swamp_description_dod", "Sting, Serpent of Regret. Feel free to offer suggestions for this description."},
            {"item_bow_mountain_dod", "Razorwind, Ferocity of Redemption"},
            {"item_bow_mountain_description_dod", "Razorwind, Ferocity of Redemption. Feel free to offer suggestions for this description."},
            {"item_bow_plains_dod", "Stryker, Guardian of the Sun"},
            {"item_bow_plains_description_dod", "Stryker, Guardian of the Sun. Feel free to offer suggestions for this description."},
            {"item_bow_mistlands_dod", "Soulstring, Memory of the Damned"},
            {"item_bow_mistlands_description_dod", "Soulstring, Memory of the Damned. Feel free to offer suggestions for this description."},
            {"item_bow_deepnorth_dod", "Siren's Song, Vengeance of the Incoming Storm"},
            {"item_bow_deepnorth_description_dod", "Siren's Song, Vengeance of the Incoming Storm. Feel free to offer suggestions for this description."},
            {"item_sword_meadows_dod", "Betrayer, Ferocity of Hate"},
            {"item_sword_meadows_description_dod", "Betrayer, Ferocity of Hate. Feel free to offer suggestions for this description."},
            {"item_sword_swamp_dod", "Ghost Reaver, Crusader of the Plague"},
            {"item_sword_swamp_description_dod", "Ghost Reaver, Crusader of the Plague. Feel free to offer suggestions for this description."},
            {"item_sword_plains_dod", "Light's Bane, Blade of Justice"},
            {"item_sword_plains_description_dod", "Light's Bane, Blade of Justice. Feel free to offer suggestions for this description."},
            {"item_sword_mistlands_dod", "Misery, Call of Denial"},
            {"item_sword_mistlands_description_dod", "Misery, Call of Denial. Feel free to offer suggestions for this description."},
            {"item_sword_deepnorth_dod", "Fate, Frostblade of Frozen Hells"},
            {"item_sword_deepnorth_description_dod", "Fate, Frostblade of Frozen Hells. Feel free to offer suggestions for this description."},
            {"item_sword_ashlands_dod", "Hellfire, Spine of Twisted Visions"},
            {"item_sword_ashlands_description_dod", "Hellfire, Spine of Twisted Visions. Feel free to offer suggestions for this description."},
            {"item_mountainwand_dod", "Snowfall, Instrument of the Champion"},
            {"item_mountainwand_description_dod", "Snowfall, Instrument of the Champion. Feel free to offer suggestions for this description."},
            {"item_mace_deepnorth_dod", "Silence, Edge of the World"},
            {"item_mace_deepnorth_description_dod", "Silence, Edge of the World. Feel free to offer suggestions for this description."},
            {"item_mace_mistlands_dod", "Abomination, Memory of Giants"},
            {"item_mace_mistlands_description_dod", "Abomination, Memory of Giants. Feel free to offer suggestions for this description."},

            {"piece_forge_ext1_dod", "Felmetal Anvils"},
            {"piece_forge_ext2_dod", "Frometal Anvils"},
            {"piece_forge_ext3_dod", "Flametal Anvils"},

            {"item_crudearmorkit_dod", "Crude Armor Kit"},
            {"item_crudearmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_basicarmorkit_dod", "Basic Armor Kit"},
            {"item_basicarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_goodarmorkit_dod", "Good Armor Kit"},
            {"item_goodarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_greatarmorkit_dod", "Great Armor Kit"},
            {"item_greatarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_superiorarmorkit_dod", "Superior Armor Kit"},
            {"item_superiorarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_excellentarmorkit_dod", "Excellent Armor Kit"},
            {"item_excellentarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_exceptionalarmorkit_dod", "Exceptional Armor Kit"},
            {"item_exceptionalarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_extraordinaryarmorkit_dod", "Extraordinary Armor Kit"},
            {"item_extraordinaryarmorkit_description_dod", "Used for crafting Armor or can be sold to the Trader. Can be bought from the Trader or Crafted."},

            {"item_crudeweaponkit_dod", "Crude Weapon Kit"},
            {"item_crudeweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_basicweaponkit_dod", "Basic Weapon Kit"},
            {"item_basicweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_goodweaponkit_dod", "Good Weapon Kit"},
            {"item_goodweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_greatweaponkit_dod", "Great Weapon Kit"},
            {"item_greatweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_superiorweaponkit_dod", "Superior Weapon Kit"},
            {"item_superiorweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_excellentweaponkit_dod", "Excellent Weapon Kit"},
            {"item_excellentweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_exceptionalweaponkit_dod", "Exceptional Weapon Kit"},
            {"item_exceptionalweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},
            {"item_extraordinaryweaponkit_dod", "Extraordinary Weapon Kit"},
            {"item_extraordinaryweaponkit_description_dod", "Used for crafting Weapons or can be sold to the Trader. Can be bought from the Trader or Crafted."},

            {"item_oakwood_dod", "Hardwood"},
            {"item_oakwood_description_dod", "Hardwood is used in crafting"},

            {"item_trophy_icedrake", "Ice Drake Head"},
            {"item_trophy_icedrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_flamedrake", "Flame Drake Head"},
            {"item_trophy_flamedrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_arcanedrake", "Arcane Drake Head"},
            {"item_trophy_arcanedrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_poisondrake", "Poison Drake Head"},
            {"item_trophy_poisondrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_darkdrake", "Dark Drake Head"},
            {"item_trophy_darkdrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_darknessdrake", "Darkness Drake Head"},
            {"item_trophy_darknessdrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_golddrake", "Gold Drake Head"},
            {"item_trophy_golddrake_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_skeletonchar_dod", "Charred Skull"},
            {"item_trophy_skeletonchar_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_skeletonr_dod", "Brittle Skull"},
            {"item_trophy_skeletonr_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_skeletong_dod", "Pale Skull"},
            {"item_trophy_skeletong_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_frozenbones_dod", "Frozen Skull"},
            {"item_trophy_frozenbones_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_forestwolf_dod", "Forest Wolf Head"},
            {"item_trophy_forestwolf_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_direwolf_dod", "Dire Wolf Head"},
            {"item_trophy_direwolf_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_vilefang_dod", "Vilefang Head"},
            {"item_trophy_vilefang_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_frostling_dod", "Frostling Head"},
            {"item_trophy_frostlingdescription", "A Trophy, hang it up on your wall"},
            {"item_trophy_voidling_dod", "Voidling Head"},
            {"item_trophy_voidling_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_stormling_dod", "Stormling Head"},
            {"item_trophy_stormling_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_livinglava_dod", "Living Lava"},
            {"item_trophy_livinglava_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_blackdeer_dod", "Black Deer Head"},
            {"item_trophy_blackdeer_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_obgolem_dod", "Obsidian Golem Head"},
            {"item_trophy_obgolem__description", "A Trophy, hang it up on your wall"},
            {"item_trophy_lavagolem_dod", "Lava Golem Head"},
            {"item_trophy_lavagolem_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_icegolem_dod", "Ice Golem Head"},
            {"item_trophy_icegolem_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_livingwater_dod", "Living Water"},
            {"item_trophy_livingwater_description", "A Trophy, hang it up on your wall"},
            {"item_trophy_gsurtling_dod", "Greater Surtling Head"},
            {"item_trophy_gsurtling_description", "A Trophy, hang it up on your wall"}
        };
		private static Dictionary<string, string> russian = new Dictionary<string, string>() {
			{ "spawner_firedraketower_dod", "Drake Tower" },
			{ "spawner_arena_dod", "Arena Spawner" },
			{ "piece_bitterstumpaltar_dod", "Bitterstump Altar" },
			{ "object_glowmetal_dod", "Glowing Metal" },
			{ "object_rock_dod", "Rock" },
			{ "prop_worldlevel_dod", "World Level" },
			{ "prop_worldlevel_description_dod", "Level 1: Day 15 - Level 2: Day 25 - Level 3: Day 50 - Level 4: Day 100 - Level 5: Day 200" },
			{ "prop_cavemushroom_dod", "Cave Mushroom" },
			{ "item_cavemushroom_dod", "Cave Mushroom" },
			{ "item_cavemushroom_description_dod", "These come from the underworld." },

			{"animal_sheep_dod", "Овца"},
			{"animal_goat_dod", "Козел"},
			{"animal_goose_dod", "Гусь"},
			{"animal_penguin_dod", "Пингвин"},
			{"animal_salamander_dod", "Огненная саламандра"},
			{"animal_turtle_dod", "Коробчатая черепаха"},
			{"animal_rat_dod", "Крыса"},
			{"animal_greenlizard_dod", "Зеленая ящерица"},
			{"animal_brownlizard_dod", "Коричневая ящерица"},
			{"animal_spottedlizard_dod", "Пятнистая ящерица"},
			{"animal_greenfrog_dod", "Зеленая лягушка"},
			{"animal_blackfrog_dod", "Черная лягушка"},
			{"animal_spottedfrog_dod", "Пятнистая лягушка"},
			{"animal_greyrabbit_dod", "Серый кролик"},
			{"animal_brownrabbit_dod", "Коричневый кролик"},
			{"animal_giantsnail_dod", "Гигантская улитка"},

			{"item_walnuts_dod", "Грецкие орехи"},
			{"item_walnuts_description_dod", "Собранный с орехового дерева в Туманных Землях."},
			{"item_apple_dod", "Яблоки"},
			{"item_apple_description_dod", "Собранный с яблони в Туманных землях."},
			{"item_redberries_dod", "Вишни"},
			{"item_redberries_description_dod", "Собран с вишневого дерева в Туманных землях."},

			{"item_shield_bgskull_dod", "Сломанный щит Бхигшана"},
			{"item_shield_bgskull_description_dod", "Раньше это был щит Бхыгшана, пока вы не сломали его во время боя с ним. Интересно, сможешь ли ты его починить."},
			{"item_shield_byagluth_dod","Сломанный щит"},
			{"item_shield_byagluth_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bskir_dod", "Сломанный щит"},
			{"item_shield_bskir_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bmoder_dod", "Сломанный щит"},
			{"item_shield_bmoder_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bfarkas_dod", "Сломанный щит"},
			{"item_shield_bfarkas_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bbonemass_dod", "Сломанный щит"},
			{"item_shield_bbonemass_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_belder_dod", "Сломанный щит"},
			{"item_shield_belder_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bbitterstump_dod", "Сломанный щит"},
			{"item_shield_bbitterstump_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_beikthyr_dod", "Сломанный щит"},
			{"item_shield_beikthyr_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_brambone_dod", "Сломанный щит"},
			{"item_shield_brambone_description_dod", "Интересно, сможете ли вы это исправить? Не стесняйтесь предлагать предложения по этому пункту."},

			{"item_shield_yagluth_dod", "Врата смерти"},
			{"item_shield_yagluth_description_dod", "Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_skir_dod", "Куратор Уорд"},
			{"item_shield_skir_description_dod", "Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_moder_dod", "Идеальный шторм"},
			{"item_shield_moder_description_dod", "Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_farkas_dod", "Застывший свет"},
			{"item_shield_farkas_description_dod","Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bonemass_dod", "Призрачная стена"},
			{"item_shield_bonemass_description_dod", "Не стесняйтесь предлагать предложения по этому пункту."},
			{"item_shield_bhygshan_dod", "Вихрь, хранитель мертвых"},
			{"item_shield_bhygshan_description_dod", "Вы отремонтировали Щит Бхыгшана, поздравляем! Не стесняйтесь предлагать предложения по этому предмету."},
			{"item_shield_elder_dod", "Железная кора"},
			{"item_shield_elder_description_dod", "Не стесняйтесь предлагать свои предложения по этому пункту."},
			{"item_shield_bitterstump_dod", "Темное сердце"},
			{"item_shield_bitterstump_description_dod", "Не стесняйтесь предлагать свои предложения по этому пункту."},
			{"item_shield_eikthyr_dod", "Грозовое облако"},
			{"item_shield_eikthyr_description_dod", "Не стесняйтесь предлагать свои предложения по этому пункту."},
			{"item_shield_rambone_dod", "Правоохранитель"},
			{"item_shield_rambone_description_dod", "Не стесняйтесь предлагать свои предложения по этому пункту."},

			{"item_mace_bhygshan_dod", "Оскверненная боевая палица, Захват вечности"},
			{"item_mace_bhygshan_description_dod", "Оскверненная боевая палица, Захват вечности. Не стесняйтесь предлагать свои предложения для этого описания."},
			{"item_bow_blackforest_dod", "Шершень, Чистота боли"},
			{"item_bow_blackforest_description_dod", "Шершень, Чистота боли. Не стесняйтесь предлагать свои предложения для этого описания."},
			{"item_bow_swamp_dod", "Стинг, Змея сожаления"},
			{"item_bow_swamp_description_dod", "Стинг, Змей сожаления. Не стесняйтесь предлагать свои предложения для этого описания."},
			{"item_bow_mountain_dod", "Ветер бритвы, Свирепость искупления"},
			{"item_bow_mountain_description_dod", "Ветер бритвы, свирепость искупления. Не стесняйтесь предлагать свои предложения для этого описания."},
			{"item_bow_plains_dod", "Страйкер, Хранитель Солнца"},
			{"item_bow_plains_description_dod", "Страйкер, Хранитель Солнца"},
			{"item_bow_mistlands_dod", "Струна души, Память проклятых"},
			{"item_bow_mistlands_description_dod", "Струна души, Память проклятых"},
			{"item_bow_deepnorth_dod", "Песнь сирены, Месть надвигающегося шторма"},
			{"item_bow_deepnorth_description_dod", "Песнь сирены, Месть надвигающегося шторма"},
			{"item_sword_meadows_dod", "Предатель, Свирепая ненависть"},
			{"item_sword_meadows_description_dod", "Предатель, Свирепая ненависть"},
			{"item_sword_swamp_dod", "Призрачный пожиратель, крестоносец чумы"},
			{"item_sword_swamp_description_dod", "Призрачный пожиратель, крестоносец чумы"},
			{"item_sword_plains_dod", "Бич Света, Клинок Правосудия"},
			{"item_sword_plains_description_dod", "Бич Света, Клинок Правосудия"},
			{"item_sword_mistlands_dod", "Страдание, вызов отрицания"},
			{"item_sword_mistlands_description_dod", "Страдание, вызов отрицания"},
			{"item_sword_deepnorth_dod", "Судьба, Ледяной Клинок Замерзшего Ада"},
			{"item_sword_deepnorth_description_dod", "Судьба, Ледяной Клинок Замерзшего Ада"},
			{"item_sword_ashlands_dod", "Адский огонь, Хребет Искаженных Видений"},
			{"item_sword_ashlands_description_dod", "Адский огонь, Хребет Искаженных Видений"},
			{"item_mountainwand_dod", "Снегопад, орудие чемпиона"},
			{"item_mountainwand_description_dod", "Снегопад, орудие чемпиона"},
			{"item_mace_deepnorth_dod", "Тишина, край света"},
			{"item_mace_deepnorth_description_dod", "Тишина, край света"},
			{"item_mace_mistlands_dod", "Мерзость, память о гигантах"},
			{"item_mace_mistlands_description_dod", "Мерзость, память о гигантах"},

			{"piece_forge_ext1_dod", "Наковальни из фелметалла"},
			{"piece_forge_ext2_dod", "Наковальни из фрометалла"},
			{"piece_forge_ext3_dod", "Наковальни из фламетал"},

			{"item_crudearmorkit_dod", "Грубый Набор для Доспех"},
			{"item_crudearmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_basicarmorkit_dod", "Базовый Набор для Доспех"},
			{"item_basicarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_goodarmorkit_dod", "Хороший Набор для Доспех"},
			{"item_goodarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_greatarmorkit_dod", "Отличный Набор для Доспех"},
			{"item_greatarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_superiorarmorkit_dod", "Улучшенный Набор для Доспех"},
			{"item_superiorarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_excellentarmorkit_dod", "Отличный Набор для Доспех"},
			{"item_excellentarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_exceptionalarmorkit_dod", "Исключительный Набор для Доспех"},
			{"item_exceptionalarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_extraordinaryarmorkit_dod", "Необычный Набор для Доспех"},
			{"item_extraordinaryarmorkit_description_dod", "Используется для изготовления Доспехов или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},

			{"item_crudeweaponkit_dod", "Грубый Набор для Оружия"},
			{"item_crudeweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_basicweaponkit_dod", "Базовый Набор для Оружия"},
			{"item_basicweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_goodweaponkit_dod", "Хороший Набор для Оружия"},
			{"item_goodweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_greatweaponkit_dod", "Улучшенный Набор для Оружия"},
			{"item_greatweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_superiorweaponkit_dod", "Превосходный Набор для Оружия"},
			{"item_superiorweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_excellentweaponkit_dod", "Отличный Набор для Оружия"},
			{"item_excellentweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_exceptionalweaponkit_dod", "Исключительный Набор для Оружия"},
			{"item_exceptionalweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},
			{"item_extraordinaryweaponkit_dod", "Необычный Набор для Оружия"},
			{"item_extraordinaryweaponkit_description_dod", "Используется для изготовления оружия или может быть продан Торговцу. Может быть куплен у Торговца или изготовлен вручную."},

			{"item_oakwood_dod", "Твердая древесина"},
			{"item_oakwood_description_dod", "Твердая древесина используется в ремесле"},

			{"item_trophy_icedrake", "Голова Ледяного Дрейка"},
			{"item_trophy_icedrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_flamedrake", "Голова Огненного Дрейка"},
			{"item_trophy_flamedrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_arcanedrake", "Голова Загадочного Дрейка"},
			{"item_trophy_arcanedrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_poisondrake", "Голова Ядовитого Дрейка"},
			{"item_trophy_poisondrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_darkdrake", "Голова Черного Дрейка"},
			{"item_trophy_darkdrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_darknessdrake", "Голова Темного Дрейка"},
			{"item_trophy_darknessdrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_golddrake", "Голова Золотого Дрейка"},
			{"item_trophy_golddrake_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_skeletonchar_dod", "Обугленный Череп"},
			{"item_trophy_skeletonchar_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_skeletonr_dod", "Хрупкий Череп"},
			{"item_trophy_skeletonr_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_skeletong_dod", "Бледный Череп"},
			{"item_trophy_skeletong_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_frozenbones_dod", "Замороженный Череп"},
			{"item_trophy_frozenbones_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_forestwolf_dod", "Голова Лесного Волка"},
			{"item_trophy_forestwolf_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_direwolf_dod", "Голова Страшного Волка"},
			{"item_trophy_direwolf_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_vilefang_dod", "Голова Мерзкого Клыка"},
			{"item_trophy_vilefang_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_frostling_dod", "Голова Обмороженного"},
			{"item_trophy_frostlingdescription", "Трофей, повесь его у себя на стене."},
			{"item_trophy_voidling_dod", "Голова Пустого"},
			{"item_trophy_voidling_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_stormling_dod", "Голова Штормового"},
			{"item_trophy_stormling_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_livinglava_dod", "Живая Лава"},
			{"item_trophy_livinglava_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_blackdeer_dod", "Голова Черного Оленя"},
			{"item_trophy_blackdeer_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_obgolem_dod", "Голова Обсидианового Голема"},
			{"item_trophy_obgolem__description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_lavagolem_dod", "Голова Лавового Голема"},
			{"item_trophy_lavagolem_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_icegolem_dod", "Голова Ледяного Голема"},
			{"item_trophy_icegolem_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_livingwater_dod", "Живая Вода"},
			{"item_trophy_livingwater_description", "Трофей, повесь его у себя на стене."},
			{"item_trophy_gsurtling_dod", "Голова Великого Суртлинга"},
			{"item_trophy_gsurtling_description", "Трофей, повесь его у себя на стене."}
			};
		private static Dictionary<string, string> german = new Dictionary<string, string>() {

			{"animal_sheep_dod", "Schaf"},
			{"animal_goat_dod", "Ziege"},
			{"animal_goose_dod", "Gans"},
			{"animal_penguin_dod", "Pinguin"},
			{"animal_salamander_dod", "Feuersalamander"},
			{"animal_turtle_dod", "Dosenschildkröte"},
			{"animal_rat_dod", "Ratte"},
			{"animal_greenlizard_dod", "Grüne Eidechse"},
			{"animal_brownlizard_dod", "Braune Eidechse"},
			{"animal_spottedlizard_dod", "Gefleckte Eidechse"},
			{"animal_greenfrog_dod", "Grüner Frosch"},
			{"animal_blackfrog_dod", "Schwarzer Frosch"},
			{"animal_spottedfrog_dod", "Gefleckter Frosch"},
			{"animal_greyrabbit_dod", "Graues Kaninchen"},
			{"animal_brownrabbit_dod", "Braunes Kaninchen"},
			{"animal_giantsnail_dod", "Riesenschnecke"},

			{"npc_skugga_dod", "Skugga"},
			{"npc_einherjar_dod", "Einherjar"},

			{"item_walnuts_dod", "Walnüsse"},
			{"item_walnuts_description_dod", "Gesammelt von einem Walnussbaum in den Nebellanden."},
			{"item_apple_dod", "Äpfel"},
			{"item_apple_description_dod", "Gesammelt von einem Apfelbaum in den Nebellanden."},
			{"item_redberries_dod", "Kirschen"},
			{"item_redberries_description_dod", "Gesammelt von einem Kirschbaum in den Nebellanden."},

			{"item_shield_bgskull_dod", "Bhygshans zerbrochener Schild"},
			{"item_shield_bgskull_description_dod", "Früher war das Bhygshans Schild, bevor du ihn im Kampf gegen ihn zerbrochen hast. Frage mich, ob du ihn reparieren kannst."},
			{"item_shield_byagluth_dod", "Zerbrochener Schild"},
			{"item_shield_byagluth_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_bskir_dod", "Zerbrochener Schild"},
			{"item_shield_bskir_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_bmoder_dod", "Zerbrochener Schild"},
			{"item_shield_bmoder_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_bfarkas_dod", "Zerbrochener Schild"},
			{"item_shield_bfarkas_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_bbonemass_dod", "Zerbrochener Schild"},
			{"item_shield_bbonemass_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_belder_dod", "Zerbrochener Schild"},
			{"item_shield_belder_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_bbitterstump_dod", "Zerbrochener Schild"},
			{"item_shield_bbitterstump_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_beikthyr_dod", "Zerbrochener Schild"},
			{"item_shield_beikthyr_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},
			{"item_shield_brambone_dod", "Zerbrochener Schild"},
			{"item_shield_brambone_description_dod", "Frage mich, ob du das Problem beheben kannst. Fühlen Sie sich frei, Vorschläge für diesen Artikel zu machen."},

			{"item_shield_yagluth_dod", "Todespforte"},
			{"item_shield_yagluth_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_skir_dod", "Kuratorwächter"},
			{"item_shield_skir_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_moder_dod", "Perfekter Sturm"},
			{"item_shield_moder_description_dod", "Fühlen Sie sich frei zu bietenVorschläge für dieses Element. "},
			{"item_shield_farkas_dod", "Gefrorenes Licht"},
			{"item_shield_farkas_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_bonemass_dod", "Geistermauer"},
			{"item_shield_bonemass_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_bhygshan_dod", "Vortex, Konservator der Toten"},
			{"item_shield_bhygshan_description_dod", "Du hast Bhygshans Schild repariert, herzlichen Glückwunsch! Fühle dich frei, Vorschläge für diesen Gegenstand zu machen."},
			{"item_shield_elder_dod", "Eisenborke"},
			{"item_shield_elder_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_bitterstump_dod", "Dunkelherz"},
			{"item_shield_bitterstump_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_eikthyr_dod", "Gewitterwolke"},
			{"item_shield_eikthyr_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},
			{"item_shield_rambone_dod", "Vollstrecker"},
			{"item_shield_rambone_description_dod", "Sie können gerne Vorschläge für diesen Artikel machen."},

			{"item_mace_bhygshan_dod", "Entweihter Streitkolben, Griff der Ewigkeit"},
			{"item_mace_bhygshan_description_dod", "Entweihter Streitkolben, Griff der Ewigkeit. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_blackforest_dod", "Hornisse, Reinheit des Schmerzes"},
			{"item_bow_blackforest_description_dod", "Hornisse, Reinheit des Schmerzes. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_swamp_dod", "Stich, Schlange des Bedauerns"},
			{"item_bow_swamp_description_dod", "Stich, Schlange des Bedauerns. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_mountain_dod", "Klingenwind, Wildheit der Erlösung"},
			{"item_bow_mountain_description_dod", "Klingenwind, Wildheit der Erlösung. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_plains_dod", "Stryker, Hüter der Sonne"},
			{"item_bow_plains_description_dod", "Stryker, Hüter der Sonne. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_mistlands_dod", "Seelenkette, Erinnerung an die Verdammten"},
			{"item_bow_mistlands_description_dod", "Soulstring, Memory of the Damned. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_bow_deepnorth_dod", "Sirenenlied, Rache des kommenden Sturms"},
			{"item_bow_deepnorth_description_dod", "Sirenenlied, Rache des kommenden Sturms. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_meadows_dod", "Verräter, Grausamkeit des Hasses"},
			{"item_sword_meadows_description_dod", "Verräter, Grausamkeit des Hasses. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_swamp_dod", "Geisterhäscher, Kreuzfahrer der Pest"},
			{"item_sword_swamp_description_dod", "Geisterhäscher, Kreuzfahrer der Pest. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_plains_dod", "Lichts Fluch, Klinge der Gerechtigkeit"},
			{"item_sword_plains_description_dod", "Lichts Fluch, Klinge der Gerechtigkeit. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_mistlands_dod", "Elend, Ruf der Verleugnung"},
			{"item_sword_mistlands_description_dod", "Elend, Ruf der Verleugnung. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_deepnorth_dod", "Schicksal, Frostklinge der gefrorenen Höllen"},
			{"item_sword_deepnorth_description_dod", "Schicksal, Frostklinge der gefrorenen Höllen. Fühle dich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_sword_ashlands_dod", "Höllenfeuer, Rückgrat der verdrehten Visionen"},
			{"item_sword_ashlands_description_dod", "Höllenfeuer, Rückgrat der verdrehten Visionen. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_mountainwand_dod", "Schneefall, Instrument des Champions"},
			{"item_mountainwand_description_dod", "Schneefall, Instrument des Champions. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_mace_deepnorth_dod", "Stille, Rand der Welt"},
			{"item_mace_deepnorth_description_dod", "Stille, Rand der Welt. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},
			{"item_mace_mistlands_dod", "Abscheulichkeit, Erinnerung an Riesen"},
			{"item_mace_mistlands_description_dod", "Abscheulichkeit, Erinnerung an Riesen. Fühlen Sie sich frei, Vorschläge für diese Beschreibung zu machen."},

			{"piece_forge_ext1_dod", "Teufelsmetall Ambosse"},
			{"piece_forge_ext2_dod", "Frostmetall Ambosse"},
			{"piece_forge_ext3_dod", "Flammenmetal Ambosse"},

			{"item_crudearmorkit_dod", "Primitiver Rüstungsbausatz"},
			{"item_crudearmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_basicarmorkit_dod", "Grundlegender Rüstungsbausatz"},
			{"item_basicarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_goodarmorkit_dod", "Guter Rüstungsbausatz"},
			{"item_goodarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_greatarmorkit_dod", "Großer Rüstungsbausatz"},
			{"item_greatarmorkit_description_dod", "Wird zum Herstellen von Rüstungen oder Ca . verwendetn an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden. "},
			{"item_superiorarmorkit_dod", "Überlegener Rüstungsbausatz"},
			{"item_superiorarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_excellentarmorkit_dod", "Ausgezeichneter Rüstungsbausatz"},
			{"item_excellentarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_Exceptionalarmorkit_dod", "Außergewöhnlicher Rüstungsbausatz"},
			{"item_exceptionalarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_extraordinaryarmorkit_dod", "Außerordentlicher Rüstungsbausatz"},
			{"item_extraordinaryarmorkit_description_dod", "Wird zum Herstellen von Rüstungen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},

			{"item_crudeweaponkit_dod", "Primitiver Waffenbausatz"},
			{"item_crudeweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_basicweaponkit_dod", "Grundlegender Waffenbausatz"},
			{"item_basicweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_goodweaponkit_dod", "Guter Waffenbausatz"},
			{"item_goodweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_greatweaponkit_dod", "Großer Waffenbausatz"},
			{"item_greatweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_superiorweaponkit_dod", "Überlegener Waffenbausatz"},
			{"item_superiorweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_excellentweaponkit_dod", "Excellenter Waffenbausatz"},
			{"item_excellentweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_exceptionalweaponkit_dod", "Außergewöhnlicher Waffenbausatz"},
			{"item_exceptionalweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},
			{"item_extraordinaryweaponkit_dod", "Außerordentlicher Waffenbausatz"},
			{"item_extraordinaryweaponkit_description_dod", "Wird zum Herstellen von Waffen verwendet oder kann an den Händler verkauft werden. Kann beim Händler gekauft oder hergestellt werden."},

			{"item_oakwood_dod", "Hartholz"},
			{"item_oakwood_description_dod", "Hartholz wird zur Herstellung verwendet"},

			{"item_trophy_icedrake", "Eisdrachenkopf"},
			{"item_trophy_icedrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_flamedrake", "Flammendrachenkopf"},
			{"item_trophy_flamedrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_arcanedrake", "Arkandrachenkopf"},
			{"item_trophy_arcanedrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_poisondrake", "Giftdrachenkopf"},
			{"item_trophy_poisondrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_darkdrake", "Dunkeldrachenkopf"},
			{"item_trophy_darkdrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_darknessdrake", "Finsterdrachenkopf"},
			{"item_trophy_darknessdrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_golddrake", "Golddrachenkopf"},
			{"item_trophy_golddrake_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_skeletonchar_dod", "Verkohlter Schädel"},
			{"item_trophy_skeletonchar_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_skeletonr_dod", "Spröder Schädel"},
			{"item_trophy_skeletonr_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_skeletong_dod", "Blasser Schädel"},
			{"item_trophy_skeletong_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_frozenbones_dod", "Gefrorener Schädel"},
			{"item_trophy_frozenbones_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_forestwolf_dod", "Waldwolfskopf"},
			{"item_trophy_forestwolf_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_direwolf_dod", "Düsterwolfkopf"},
			{"item_trophy_direwolf_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_vilefang_dod", "Reißzahnkopf"},
			{"item_trophy_vilefang_description", "Eine Trophäe, häng sie an deine Wand"},
			{"item_trophy_frostling_dod", "Frostling-Kopf"},
			{"item_trophy_frostlingdescription", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_voidling_dod", "Leerling-Kopf"},
			{"item_trophy_voidling_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_stormling_dod", "Sturmling-Kopf"},
			{"item_trophy_stormling_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_livinglava_dod", "Lebende Lava"},
			{"item_trophy_livinglava_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_blackdeer_dod", "Schwarzhirschkopf"},
			{"item_trophy_blackdeer_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_obgolem_dod", "Obsidiangolemkopf"},
			{"item_trophy_obgolem__description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_lavagolem_dod", "Lavagolemkopf"},
			{"item_trophy_lavagolem_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_icegolem_dod", "Eisgolemkopf"},
			{"item_trophy_icegolem_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_livingwater_dod", "Lebendiges Wasser"},
			{"item_trophy_livingwater_description", "Eine Trophäe, hänge sie an deine Wand"},
			{"item_trophy_gsurtling_dod", "Großer Surtlingkopf"},
			{"item_trophy_gsurtling_description", "Eine Trophäe, häng sie an deine Wand"}
			};

		public static void init(string lang, Localization l)
        {
            lcl = l;
            if (lang == "Russian")
            {
                t = russian;
            }
			else if (lang == "English")
			{
				t = english;
			}
			else
			{
				t = german;
			}
		}
        public static void AddWord(object[] element)
        {
            MethodInfo meth = AccessTools.Method(typeof(Localization), "AddWord", null, null);
            meth.Invoke(lcl, element);
        }
        public static void UpdateDictinary()
        {
            string missing = "Missing Words:";
            foreach (var el in english)
            {
                if (t.ContainsKey(el.Key))
                {
                    AddWord(new object[] { el.Key, t[el.Key] });
                    continue;
                }
                AddWord(new object[] { el.Key, el.Value });
                missing += el.Key;
            }
        }

        [HarmonyPatch(typeof(Localization), "SetupLanguage")]
        public static class DoDLocalizationPatch
        {
            public static void Postfix(Localization __instance, string language)
            {
                init(language, __instance);
                UpdateDictinary();
            }
        }
    }
}
